version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    environment:
      NODE_ENV: production
      NAME_API: API
      CORS_URL: '*'
      PREFIX_API: /api/v1.0
      PG_URI: mongodb://root:root@mongo:27017
      PG_DATABASE: prueba-backend-cidenet
      EMAIL_DOMAIN: cidenet.com.co
      RIJNDAEL_KEY: cidenet
      SEED: sdfgsdffgsf
      EXPIRES_IN: 15
    container_name: app
    restart: unless-stopped
    ports:
      - 5000:9000
    links:
      - postgres

  postgres:
    container_name: prueba-cidenet-db
    image: postgres:12.7-alpine3.14
    restart: always
    volumes:
      - './postgres-data/:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: cidenet
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
